export const translation = {
    labels: {
        avg: 'Avarage',
        min: 'Minimum',
        max: 'Maximum',
        sum: 'Sum',
        std: 'Standard Deviation',
        cancel: 'Cancel',
        add: 'Add',
        update: 'Update',
        delete: 'Delete'
    },
    Dashboard: {
        alarm_title: "Form alarm",
        delete_alarm: "Delete alarm",
        delete_alarm_description: "This process is not reversible",
        title : "Welcome to the Dashboard",
        subtitle : "Here is your overview",
        graph_title_ffm : "Average of the site",
        graph_title_smo : "Average of site: ",
        graph_title_smo1: "for KPI: ",
        create_alarm : "Add Alarm",
        show_graph : "Show New Graph",
        loading_kpis : "Loading KPIs ...",
        error_kpis : "Error loading KPIs",
        select_operation: "Select Operation",
        select_days: "Select Granularity Days",
        day: 'day',
        days: 'days',
        select_machines : "Select Granularity Machines",
        by_site : "By site",
        by_category : "By category",
        select_site : "Select Site",
        create_graph : "Create new graph",
        create_button_loading: "Creating",
    },
    CreateReport : {
        name: "Name",
        language: "Language",
        select_language: "Select Language",
        it : "Italian",
        eng : "English",
        fr : "French",
        site: "Site",
        select_site: "Select Site",
        start_date: "Start Date",
        end_date: "End Date",
        op : "Aggregation Operation",
        select_op : "Select Operation",
        op_avg : "Avarage",
        op_min : "Min",
        op_max: "Max",
        op_sum: "Sum",
        op_std: "Standard Deviation",
        kpis : "Select KPIs",
        select_edate: "Select End Date",
        select_sdate: "Select Start Date",
        insert : "Enter report name",
        generate_button : "Generate Report",
        generate_loading : "Generating ...",
        press_ctrl: "Press ctrl to select multiple"
    },

    KPIs : {
        tab_anom : "Anomalies",
        tab_energy : "Energy Consumption",
        tab_cost : "Costs",
        tab_cycle : "Cycles",
        anom_1 : "Energy Anomalies",
        anom_2 : "Time Anomalies",
        anom_3 : "Cycle Quality Anomalies",
        anom_4: "Cycle Time Anomalies",
        energy_1 : "Consumption Trend",
        energy_2 : "Idle Consumption",
        energy_3 : "Working Consumption",
        cost_1 : "Cost Breakdown",
        cost_2 : "Idle Cost",
        cost_3 : "Working Cost",
        cycle_1 : "Cycles Breakdown",
        cycle_2 : "Good Cycle Trend",
        cycle_3 : "Bad Cycle Trend",
        pie_cost_1 : "Working",
        pie_cost_2 : "Idle",
        pie_cycle_1 : "Good",
        pie_cycle_2 : "Bad",
        trend : "Site Avarage",
        loading: "Loading ..."
    },

    Chatbot : {
        message: "Write a message...",
        sorry: "Sorry, something went wrong. Please try again later!",
        subtitle: "This is AI-powered chatbot, it can make mistakes. Consider checking important information."
    },

    Report : {
        title: "Report History",
        subtitle: "Welcome to the report page. Here you can manage your reports.",
        create_report: "Create Report",
        loading: "Loading reports...",
        no_reports: "No reports available",
        header_1 : "Name",
        header_2 : "Download",
        header_3 : "Delete"
    },

    Alarm: {
        title: "Alarms",
        subtitle: "Welcome to the alarm page. Here you can manage your alarms.",
        create_alarm: "Create alarm",
        no_alarms: "No alarm available",
        threshold: "Threshold",
        threshold_type: "Type",
        kpi: 'KPI',
        op: 'Operation',
        site: 'Site',
        machine: 'Machine',
        created_at: "Created at",
        active: "Active",
        delete: "Delete",
        UPPER_BOUND: "Upper bound",
        LOWER_BOUND: "Lower bound",
        all_machines: "All machines",
        enabled: "Enabled"
    },

    Settings : {
        settings: "Settings",
        account: "Account",
        connected_devices : "Connected Devices",
        notifications : "Notifications",
        language : "Language",
        accessibility : "Accessibility",
        help : "Help",
        help_header : "Help page",
        help_text : "Help page with useful links",
        accessibility_header : "Accessibility Settings",
        accessibility_text : "Manage your accessibility settings here.",
        language_header : "Language Settings",
        language_text : "Manage your language settings here.",
        devices_header : "Connected Devices",
        devices_text: "Manage your connected devices here.",
        notifications_header : "Notifications Settings",
        notifications_text: "Here you can update your notifications information.",
        account_header: "Account Settings",
        account_text: "Manage your account settings here.",
    },

    Machines : {
        title: "Machine Dashboard",
        active: 'Active',
        inactive: 'Inactive',
    },

    Sites :{
        title: "Manifacturing Sites",
        alerts: "Alerts:",
        tot_machines: "Total Machines:",
        last_maint: "Last Maintenance:",
        details: "View Details",
        close_button: "Close",
    },
    SideBar: {
        Dashboard: "Dashboard",
        Alarm: "Alarms",
        Sites: "Sites",
        Machines: "Machines",
        Report: "Report",
        Settings: "Settings",
        Logout: "Logout",
    },

    Graph:{
        header: "Generated Graph",
        label: "Value"
    }
}