export const translation = {
    labels: {
        avg: "Media",
        min: "Min",
        max: "Max",
        sum: "Somma",
    },
    Dashboard: {
        title: "Benvenuto nella Dashboard",
        subtitle: "Ecco la tua panoramica",
        graph_title_ffm: "Tempo medio di lavoro",
        graph_title_smo: "Tempo medio di lavoro del sito",
        create_alarm: "Aggiungi Allarme",
        show_graph: "Mostra Nuovo Grafico",
        loading_kpis: "Caricamento KPIs ...",
        error_kpis: "Errore nel caricamento dei KPIs",
        select_operation: "Seleziona Operazione",
        select_days: "Seleziona Granularità Giorni",
        day: "giorno",
        days: "giorni",
        select_machines: "Seleziona Granularità Macchine",
        by_site: "Per sito",
        by_category: "Per categoria",
        select_site: "Seleziona Sito",
        create_graph: "Crea nuovo grafico",
        create_button_loading: "Creazione in corso",
    },
    CreateReport: {
        name: "Nome",
        language: "Lingua",
        select_language: "Seleziona Lingua",
        it: "Italiano",
        eng: "Inglese",
        fr: "Francese",
        site: "Sito",
        select_site: "Seleziona Sito",
        start_date: "Data di Inizio",
        end_date: "Data di Fine",
        op: "Operazione di Aggregazione",
        select_op: "Seleziona Operazione",
        op_avg: "Media",
        op_min: "Min",
        op_max: "Max",
        op_sum: "Somma",
        kpis: "Seleziona KPIs",
        generate_button: "Genera Report",
        generate_loading: "Generazione in corso ...",
        press_ctrl: "Premi ctrl per selezionare più elementi",
    },

    KPIs: {
        tab_anom: "Anomalie",
        tab_energy: "Consumo Energetico",
        tab_cost: "Costi",
        tab_cycle: "Cicli",
        anom_1: "Anomalie Energetiche",
        anom_2: "Anomalie Temporali",
        anom_3: "Anomalie di Qualità Ciclo",
        anom_4: "Anomalie di Tempo Ciclo",
        energy_1: "Trend di Consumo",
        energy_2: "Consumo a Riposo",
        energy_3: "Consumo durante il Lavoro",
        cost_1: "Ripartizione dei Costi",
        cost_2: "Costo a Riposo",
        cost_3: "Costo durante il Lavoro",
        cycle_1: "Ripartizione dei Cicli",
        cycle_2: "Trend dei Buoni Cicli",
        cycle_3: "Trend dei Cicli Difettosi",
        pie_cost_1: "Lavoro",
        pie_cost_2: "Riposo",
        pie_cycle_1: "Buoni",
        pie_cycle_2: "Difettosi",
    },

    Chatbot: {
        message: "Scrivi un messaggio...",
    },

    Report: {
        title: "Cronologia dei Report",
        subtitle: "Benvenuto nella pagina dei report. Qui puoi gestire i tuoi report.",
        create_button: "Crea Report",
        header_1: "Nome",
        header_2: "Elimina",
    },

    Settings: {
        settings: "Impostazioni",
        account: "Account",
        connected_devices: "Dispositivi Collegati",
        notifications: "Notifiche",
        language: "Lingua",
        accessibility: "Accessibilità",
        help: "Aiuto",
        help_header: "Pagina di Aiuto",
        help_text: "Pagina di aiuto con link utili",
        accessibility_header: "Impostazioni di Accessibilità",
        accessibility_text: "Gestisci le impostazioni di accessibilità qui.",
        language_header: "Impostazioni della Lingua",
        devices_header: "Dispositivi Collegati",
        devices_text: "Gestisci i dispositivi collegati qui.",
        notifications_header: "Impostazioni delle Notifiche",
        notifications_text: "Aggiorna qui le informazioni sulle notifiche.",
        account_header: "Impostazioni Account",
        account_text: "Gestisci le impostazioni del tuo account qui.",
    },

    Machines: {
        title: "Dashboard Macchine",
    },

    Sites: {
        title: "Siti di Produzione",
        alerts: "Allarmi:",
        tot_machines: "Totale Macchine:",
        last_maint: "Ultima Manutenzione:",
        details: "Visualizza Dettagli",
        close_button: "Chiudi",
    },
};
