export const translation = {
    labels: {
        avg: "Media",
        min: "Min",
        max: "Max",
        sum: "Somma",
        std: 'Deviazione Standard',
        cancel: 'Annulla',
        add: 'Aggiungi',
        update: 'Modifica',
        delete: 'Elimina'
    },
    Dashboard: {
        alarm_title: "Form allarme",
        delete_alarm: "Elimina allarme",
        delete_alarm_description: "Questo processo non è reversibile.",
        title: "Benvenuto nella Dashboard",
        subtitle: "Ecco la tua panoramica",
        graph_title_ffm: "Media del sito per la KPI:",
        graph_title_smo: "Media del sito: ",
        graph_title_smo1: "per la KPI: ",
        create_alarm: "Aggiungi Allarme",
        show_graph: "Mostra Nuovo Grafico",
        loading_kpis: "Caricamento KPIs ...",
        error_kpis: "Errore nel caricamento dei KPIs",
        select_operation: "Seleziona Operazione",
        select_days: "Seleziona Granularità Giorni",
        day: "giorno",
        days: "giorni",
        select_machines: "Seleziona Granularità Macchine",
        by_site: "Per sito",
        by_category: "Per categoria",
        select_site: "Seleziona Sito",
        create_graph: "Crea nuovo grafico",
        create_button_loading: "Creazione in corso",
    },

    CreateReport: {
        name: "Nome",
        language: "Lingua",
        select_language: "Seleziona Lingua",
        it: "Italiano",
        eng: "Inglese",
        fr: "Francese",
        site: "Sito",
        select_site: "Seleziona Sito",
        start_date: "Data di Inizio",
        end_date: "Data di Fine",
        op: "Operazione di Aggregazione",
        select_edate: "Seleziona Data Fine",
        select_sdate: "Seleziona Data Inizo",
        select_op: "Seleziona Operazione",
        insert : "Inserisci il nome del report",
        op_avg: "Media",
        op_min: "Min",
        op_max: "Max",
        op_sum: "Somma",
        op_std: "Deviazione Standard",
        kpis: "Seleziona KPIs",
        generate_button: "Genera Report",
        generate_loading: "Generazione in corso ...",
        press_ctrl: "Premi ctrl per selezionare più elementi",
    },

    KPIs: {
        tab_anom: "Anomalie",
        tab_energy: "Consumo Energetico",
        tab_cost: "Costi",
        tab_cycle: "Cicli",
        anom_1: "Anomalie sull'Energia",
        anom_2: "Anomalie sul Tempo",
        anom_3: "Anomalie sulla Qualità dei Cicli",
        anom_4: "Anomalie sul Tempo dei Cicli",
        energy_1: "Trend del Consumo",
        energy_2: "Consumo a Riposo",
        energy_3: "Consumo durante il Lavoro",
        cost_1: "Analisi dei Costi",
        cost_2: "Costo a Riposo",
        cost_3: "Costo durante il Lavoro",
        cycle_1: "Analisi dei Cicli",
        cycle_2: "Trend dei Cicli buoni",
        cycle_3: "Trend dei Cicli Difettosi",
        pie_cost_1: "Lavoro",
        pie_cost_2: "Riposo",
        pie_cycle_1: "Buoni",
        pie_cycle_2: "Difettosi",
        trend : "Media del Sito",
        loading: "Caricamento ..."
    },

    Chatbot: {
        message: "Scrivi un messaggio...",
        sorry: "Scusa, qualcosa è andato storto. Per favore, prova di nuovo più tardi!",
        subtitle: "Questo è un chatbot alimentato da IA, potrebbe commettere errori. Considera di controllare le informazioni importanti."
    },

    Report: {
        title: "Cronologia dei Report",
        subtitle: "Benvenuto nella pagina dei report. Qui puoi gestire i tuoi report.",
        loading: "Caricamento report...",
        no_reports: "Nessun report disponibile",
        create_report: "Crea Report",
        header_1: "Nome",
        header_2: "Scarica",
        header_3: "Elimina"
    },

    Alarm: {
        title: "Avvisi",
        subtitle: "Benvenuto nella pagina degli avvisi. Qui puoi gestire i tuoi avvisi.",
        create_alarm: "Crea avviso",
        no_alarms: "Nessum avviso",
        threshold: "Limite",
        threshold_type: "Tipo",
        kpi: 'Indice',
        site: 'Sito',
        machine: 'Macchina',
        created_at: "Creato il",
        active: "Attivo",
        delete: "Elimina",
        UPPER_BOUND: "Limite superiore",
        LOWER_BOUND: "Limite inferiore",
        all_machines: "Tutte le macchine"
    },

    Settings: {
        settings: "Impostazioni",
        account: "Account",
        connected_devices: "Dispositivi Collegati",
        notifications: "Notifiche",
        language: "Lingua",
        accessibility: "Accessibilità",
        help: "Aiuto",
        help_header: "Pagina di Aiuto",
        help_text: "Pagina di aiuto con link utili",
        accessibility_header: "Impostazioni di Accessibilità",
        accessibility_text: "Gestisci le impostazioni di accessibilità qui.",
        language_header: "Impostazioni della Lingua",
        language_text : "Gestisci le impostazioni sulla lingua qui.",
        devices_header: "Dispositivi Collegati",
        devices_text: "Gestisci i dispositivi collegati qui.",
        notifications_header: "Impostazioni delle Notifiche",
        notifications_text: "Aggiorna qui le informazioni sulle notifiche.",
        account_header: "Impostazioni Account",
        account_text: "Gestisci le impostazioni del tuo account qui.",
    },

    Machines: {
        title: "Pagina delle Macchine",
        active: 'Attivo',
        inactive: 'Inattivo',
    },

    Sites: {
        title: "Siti di Produzione",
        alerts: "Allarmi:",
        tot_machines: "Numero di Macchine:",
        last_maint: "Ultima Manutenzione:",
        details: "Visualizza Dettagli",
        close_button: "Chiudi",
    },

    SideBar: {
        Dashboard: "Schermata iniziale",
        Alarm: "Avvisi",
        Sites: "Siti",
        Machines: "Macchine",
        Report: "Report",
        Settings: "Impostazioni",
        Logout: "Disconnettersi",
    },

    Graph:{
        header: "Grafo Generato",
        label: "Valore"
    }
};
